---
kind: pipeline
type: docker
name: Building dev

platform:
  os: linux
  arch: amd64

node:
  drone: ch1

trigger:
  event:
    exclude:
      - tag

steps:
  - name: docker
    image: thegeeklab/drone-docker-buildx:23
    privileged: true
    settings:
      username: ch1ch1
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
      password:
        from_secret: dockerhub_token
      repo: ch1ch1/squid
      tags:
        - ${DRONE_STAGE_OS}-alpine-dev

  - name: notification
    image: plugins/webhook
    settings:
      urls:
        from_secret: webhookgotify
      content_type: application/json
      template: |
        {
         "message": "{{ repo.owner }} as updated {{ repo.name }} with {{ build.status }}.",
         "priority": 4,
         "title": "{{ repo.name }} build"
        }
    when:
      status: [success, failure]
---
kind: pipeline
type: docker
name: Building

platform:
  os: linux
  arch: amd64

node:
  drone: ch1

trigger:
  event:
    include:
      - tag

steps:
  - name: docker
    image: thegeeklab/drone-docker-buildx:23
    privileged: true
    settings:
      username: ch1ch1
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
      password:
        from_secret: dockerhub_token
      repo: ch1ch1/squid
      tags:
        - latest
        - ${DRONE_TAG}-${DRONE_STAGE_OS}-alpine

  - name: push README dockerhub
    image: chko/docker-pushrm:1
    environment:
      DOCKER_PASS:
        from_secret: dockerhub_token
      DOCKER_USER: ch1ch1
      PUSHRM_FILE: /drone/src/README.md
      PUSHRM_SHORT: Alpine linux squid container
      PUSHRM_TARGET: ch1ch1/squid

  - name: notification
    image: plugins/webhook
    settings:
      urls:
        from_secret: webhookgotify
      content_type: application/json
      template: |
        {
         "message": "{{ repo.owner }} as updated {{ repo.name }} with {{ build.status }}.",
         "priority": 4,
         "title": "{{ repo.name }} build"
        }
    when:
      status: [success, failure]

---
kind: signature
hmac: ad462484f3e9b8e289efc1286f3b151ca779cd3bc893cfa21108f90e0a0e97c0

...
