---
kind: pipeline
type: docker
name: Building..
node:
  drone: ch1

steps:
- name: build & push
  image: plugins/docker
  settings:
    repo: ch1ch1/squid
    tags: [ "alpine3.14","latest" ]
    username: ch1ch1
    password:
      from_secret: dockerhub-password
- name: notification
  image: plugins/webhook
  settings:
    urls:
     from_secret: webhookgotify
    content_type: application/json
    template: |
      {
       "message": "{{ repo.owner }} as updated {{ repo.name }} with {{ build.status }}.",
       "priority": 4,
       "title": "{{ repo.name }} build"
      }
  when:
    status: [ success, failure ]
---
kind: signature
hmac: 6be87773e75c0d47c7b04b0b7abab3d2199e91241ab8596881789ab6ece81c6a

...
