---
kind: pipeline
type: docker
name: Building..
node:
  drone: ch1

steps:
- name: build & push
  image: plugins/docker
  settings:
    repo: ch1ch1/squid
    tags: [ "3.16","latest" ]
    username: ch1ch1
    password:
      from_secret: dockerhub_token
- name: notification
  image: plugins/webhook
  settings:
    urls:
     from_secret: webhookgotify
    content_type: application/json
    template: |
      {
       "message": "{{ repo.owner }} as updated {{ repo.name }} with {{ build.status }}.",
       "priority": 4,
       "title": "{{ repo.name }} build"
      }
  when:
    status: [ success, failure ]
---
kind: signature
hmac: dfb5ce1586f92918a62c4f64c9f74d77d57e9efa92e52e32633268d1865bc82a

...
