kind: pipeline
type: docker
name: Building..
node:
  drone: ch1
  drone: nimi

steps:
- name: build & push
  image: plugins/docker
  settings:
    repo: ch1ch1/squid
    tags: [ "alpine3.12","latest" ]
    username: ch1ch1
    password:
      from_secret: dockerhub-password
----
kind: pipeline
type: exec
name: Publishing..
clone:
  disable: true
depends_on:
  - Building..

steps:
- name: Pull
  commands:
   - docker pull ch1ch1/squid
- name: Update
  commands:
  - service docker-squid restart
