---
kind: pipeline
type: docker
name: Building

platform:
  os: linux
  arch: amd64

node:
  drone: ch1

trigger:
  event:
    include:
      - tag

steps:
  - name: docker
    image: thegeeklab/drone-docker-buildx:23
    privileged: true
    settings:
      labels: 
      username: ch1ch1
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v6
        - linux/arm/v7
      password:
        from_secret: dockerhub_token
      repo: ch1ch1/squid
      tags:
        - latest
        - ${DRONE_STAGE_OS}-alpine-${DRONE_TAG}

  - name: pushrm-dockerhub
    image: chko/docker-pushrm:1
    environment:
      DOCKER_PASS:
        from_secret: docker_password
      DOCKER_USER:
        from_secret: docker_username
      PUSHRM_FILE: README.md
      PUSHRM_SHORT: Alpine linux squid container
      PUSHRM_TARGET: ch1ch1/squid

  - name: notification
    image: plugins/webhook
    settings:
      urls:
        from_secret: webhookgotify
      content_type: application/json
      template: |
        {
         "message": "{{ repo.owner }} as updated {{ repo.name }} with {{ build.status }}.",
         "priority": 4,
         "title": "{{ repo.name }} build"
        }
    when:
      status: [success, failure]

---
kind: signature
hmac: 4fae77257e73660f7437111521e647c09f1d24c6c2bf95b25bdc1f8a16fe36f5

...
