kind: pipeline
type: docker
name: Building..

steps:
- name: build & push
  image: plugins/docker
  settings:
    repo: ch1ch1/squid
    tags:
    - alpine3.12
    - latest
    username: ch1ch1
    password:
      from_secret: dockerhub-password
----
kind: pipeline
type: exec
name: Publishing..

clone:
  disable: true
depends_on:
  - Building..
steps:
- name: Pulling
  commands:
   - docker pull ch1ch1/squid
- name: Updating
  commands:
  - service docker-squid restart
- name: Cleaning
  commands:
   - sleep 10
   - docker system prune --all -f
