kind: pipeline
type: docker
name: Building..
node:
  drone: ch1
  drone: nimi

steps:
- name: build & push
  image: plugins/docker
  settings:
    repo: ch1ch1/squid
    tags: [ "alpine3.12","latest" ]
    username: ch1ch1
    password:
      from_secret: dockerhub-password
- name: gotify
  image: fredix/arm64v8-alpine-drone-gotify
  settings:
    gotifytoken:
      from_secret: plugin_gotifytoken
    gotifyendpoint:
      from_secret: plugin_gotifyendpoint
    gotifytitle:
      from_secret: plugin_gotifytitle
    gotifypriority:
      from_secret: plugin_gotifypriority
    message: >
      {{#success build.status}}
        build {{build.number}} succeeded on {{repo.name}}. Good job {{build.author}}  {{build.link}}
      {{else}}
        build {{build.number}} failed on {{repo.name}}. Fix me please {{build.author}}  {{build.link}}
      {{/success}}
  when:
    status: [ success, failure ]
